import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:revels20/main.dart';
import 'package:revels20/models/UserModel.dart';
import 'package:shared_preferences/shared_preferences.dart';
// import 'package:techtatva19/organizers/events.dart';
// import 'package:techtatva19/organizers/proshow.dart';
// import '../organizers/events.dart';
// import '../organizers/proshow.dart';
// import '../organizers/registration.dart';
